### PR TITLE
Swap foreach and reduce

### PR DESCRIPTION
**Pull request by mooreryan**
So I was doing some profiling of the code (due to issue #28) and one of the things I found was swapping the `foreach() ... %do%` with `Reduce ... lapply` gave a pretty noticeable speedup.

## Tests

The dataset I tested on was `lee_phylum` from the [Getting Started vignette](https://github.com/adw96/DivNet/blob/master/vignettes/getting-started.Rmd).

For the original, I got the following runtimes: 

- 67.97s
- 49.73s
- 65.99s
- 34.78s

For the shorter runtime, it didn't hit the garbage collector, but for the other ones it did.

For the Reduce version:

- 25.38s
- 25.48s
- 57s

For the longer runtime it hit the garbage collector, but for the other ones it did not.

Not sure exactly why the Reduce lapply version is faster than the foreach %do%, but it may have to do with the foreach %do% way hitting the GC more often.  But the reduce version is also faster even when neither hit the GC.

 (Also worth noting that the Docker container I'm running on has only 2 GB of ram.)

## Profiles

Here is some of the output from the profiling runs that I did using `profvis`.

[profiles.zip](https://github.com/adw96/DivNet/files/3383527/profiles.zip)

### CODE REVIEW

**Comment by mooreryan** [comment]
The next slowest function is this one: https://github.com/adw96/DivNet/blob/1c17836debf0b3156163e7f7591191c28b29f870/R/MCrow.R#L17

**Comment by adw96** [comment]
Wow, thanks, Ryan! I'm going to have to investigate this a little. @bryandmartin is the `%do%` expert. Bryan, any ideas what's going on here?

**Comment by mooreryan** [comment]
> The next slowest function is this one:
> 
> https://github.com/adw96/DivNet/blob/1c17836debf0b3156163e7f7591191c28b29f870/R/MCrow.R#L17

Regarding this function....I precomputed all the random values before entering the `for` loop.  This saved about 30% of the overall runtime.  (see this commit: https://github.com/adw96/DivNet/pull/29/commits/0502fa9d692087117f1bd53ad400a3524ee6fac4)

Here are the before and after line-by-line profiles for that function.

Original...

original

Precomputed values...

precomputed_rand_vals

**Comment by mooreryan** [comment]
`crossprod()` looks like the next most used function...looking into whether switching to an optimized BLAS implementation like OpenBLAS will help speed that up.

**Comment by mooreryan** [comment]
One last note...I tried parallelizing the code in a whole bunch of different ways and trying different sections of the code, but each of them was slower than the "serial" version.  What kind of speedup do you normally see with multiple cores?

**Comment by bryandmartin** [comment]
Regarding Reduce vs %do%, I'm not sure why one is faster than the other, but there should be no problem switching, especially if Reduce is more memory friendly.

**Comment by adw96** [comment]
@mooreryan -- Thank you so much for looking into this and submitting a pull request! We really appreciate your time.

@bryandmartin  -- Bryan please triple-check that this is doing exactly the same thing, even if the random number seeds are different. I think we have some test_that tests for the right answer in some lines in some known situations scenarios

**Comment by adw96** [comment]
@bryandmartin What is currently breaking the checks? Let's get this fixed first before approving pull requests

**Comment by bryandmartin** [comment]
@adw96 The checks are failing due to AppVeyor, not the Travis checks. I'm actually not sure what the AppVeyor checks are doing. I didn't add those. I've opened this as a pull request to run Travis checks.

**Comment by adw96** [comment]
@bryandmartin I just deleted AppVeyor checks. Travis is good enough for me.

**Pull request merged**
